import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, MapPin, Plus } from "lucide-react";
import { cityService } from "@/services/city-service";
import { ProposalGrid } from "@/components/ui";
export default function PlacePage({ params }: { params: { id: string } }) {
  const place = cityService.getPlace(params.id); if (!place) return <main className="pt-40 text-center">Platsen hittades inte.</main>;
  const proposals = cityService.getPlaceProposals(place.id);
  const contributors = [...new Map(proposals.map(proposal => [proposal.author.id, proposal.author])).values()];
  return <main className="px-5 pb-20 pt-32 sm:px-10"><div className="mx-auto max-w-7xl"><Link href="/explore" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/> Tillbaka till utforska</Link><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div className="relative h-[380px] overflow-hidden rounded-[2rem]">  <Image sizes="(max-width: 1024px) 100vw, 50vw" src={place.image} alt={place.name} fill className="object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/60 to-transparent p-7 text-white"><span className="rounded-full bg-white/20 px-3 py-1 text-xs backdrop-blur">{place.category}</span><h1 className="mt-3 text-4xl font-semibold">{place.name}</h1></div></div><div className="flex flex-col justify-center"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-sage">OM PLATSEN</p><h2 className="text-3xl font-semibold tracking-tight">En plats värd att utveckla.</h2><p className="mt-5 max-w-lg text-lg leading-relaxed text-slate-500">{place.description}</p><div className="mt-7 flex items-center gap-2 text-sm text-slate-500"><MapPin size={17} className="text-sage"/> {place.city} · {place.lat.toFixed(3)}, {place.lng.toFixed(3)}</div><div className="mt-8"><Link href="/create" className="inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white"><Plus size={16}/> Lägg till ett förslag</Link></div></div></div><div className="mt-20 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-sage">FÖRSLAG FRÅN GEMENSKAPEN</p><h2 className="text-3xl font-semibold">{proposals.length} visioner för platsen</h2></div>{contributors.length > 0 && <div className="rounded-2xl border border-black/5 bg-white px-4 py-3 dark:border-white/10 dark:bg-[#201b35]"><p className="mb-2 text-xs text-slate-400">{contributors.length === 1 ? "Förslaget är skapat av" : `${contributors.length} personer har lagt förslag`}</p><div className="flex flex-wrap items-center gap-2">{contributors.map(contributor => <Link key={contributor.id} href={`/profile?user=${contributor.id}`} title={`Visa ${contributor.name}s profil`} className="flex items-center gap-2 rounded-full pr-2 text-sm font-semibold transition hover:bg-mint dark:hover:bg-[#292044]"><Image src={contributor.avatar} alt={`Profilbild för ${contributor.name}`} width={28} height={28} className="rounded-full"/><span>{contributor.name}</span></Link>)}</div></div>}</div><div className="mt-8"><ProposalGrid proposals={proposals} compact/></div></div></main>;
}
